apiVersion: v1
kind: Service
metadata:
  name: spring-mongodb-crud-application
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32226
  selector:
    app: spring-mongodb-crud-application
  type: NodePort
